install: yarn
language: node_js 
before_script: 
before_script:
    - node_modules/malta/src/bin.js source/build.json
    - nvm install 11.10.0
    - npm install -g yarn
    - yarn install
script:
- yarn build
- yarn test
after_success:
- yarn coveralls
node_js:
  - "11.10.0"